// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8c4NEftjV95e7vipJrGueAuAAU4TsUHo',
    appId: '1:491777054796:web:53962f85a4d9dc61dc3ce9',
    messagingSenderId: '491777054796',
    projectId: 'chat-app-4fe2d',
    authDomain: 'chat-app-4fe2d.firebaseapp.com',
    storageBucket: 'chat-app-4fe2d.firebasestorage.app',
    measurementId: 'G-MTV1CGH118',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfX5t_hFze90n8vM2zRIWblTjHKvwVMEY',
    appId: '1:491777054796:android:222eea1af6ab961adc3ce9',
    messagingSenderId: '491777054796',
    projectId: 'chat-app-4fe2d',
    storageBucket: 'chat-app-4fe2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXPsw4srBpXTWW03d-wiLE_STTM-zI3Gs',
    appId: '1:491777054796:ios:f9d38d9b10ad2f95dc3ce9',
    messagingSenderId: '491777054796',
    projectId: 'chat-app-4fe2d',
    storageBucket: 'chat-app-4fe2d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXPsw4srBpXTWW03d-wiLE_STTM-zI3Gs',
    appId: '1:491777054796:ios:f9d38d9b10ad2f95dc3ce9',
    messagingSenderId: '491777054796',
    projectId: 'chat-app-4fe2d',
    storageBucket: 'chat-app-4fe2d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8c4NEftjV95e7vipJrGueAuAAU4TsUHo',
    appId: '1:491777054796:web:2b28668be5b6d60ddc3ce9',
    messagingSenderId: '491777054796',
    projectId: 'chat-app-4fe2d',
    authDomain: 'chat-app-4fe2d.firebaseapp.com',
    storageBucket: 'chat-app-4fe2d.firebasestorage.app',
    measurementId: 'G-F8FG19L5GH',
  );
}
